export const CategoryAction = {
  ADD_CATEGORIES: 'CATEGORY_ADD_CATEGORIES',
  ADD_CATEGORY: 'CATEGORY_ADD_CATEGORY',
  ADD_EMPTY_ROW: 'ADD_EMPTY_ROW',
  REMOVE_EMPTY_ROW: 'REMOVE_EMPTY_ROW',
  EDIT_START: 'CATEGORY_EDIT_START',
  EDIT_END: 'CATEGORY_EDIT_END',
  EDIT_DATA: 'CATEGORY_EDIT_DATA',
  UPDATE: 'CATEGORY_UPDATE',
  REMOVE: 'CATEGORY_REMOVE',
};

export const MessageAction = {
  SHOW_MESSAGE: 'SHOW_INFO_MESSAGE',
  HIDE_MESSAGE: 'HIDE_INFO_MESSAGE',
};

export const InputErrorAction = {
  ADD: 'ERROR_ADD',
  REMOVE_ALL: 'ERROR_REMOVE_ALL',
};

export const DeleteAction = {
  SHOW_DIALOG: 'SHOW_DIALOG',
  HIDE_DIALOG: 'HIDE_DIALOG',
};

export const HoverAction = {
  OVER: 'HOVER_OVER',
  OUT: 'HOVER_OUT',
};

export const InitialAction = {
  INITIAL_STATE: '@@INIT',
};
