export const SkillAction = {
  ADD_SKILLS: 'SKILL_ADD_SKILLS',
  ADD_SKILL: 'SKILL_ADD_SKILL',
  ADD_EMPTY_ROW: 'ADD_EMPTY_ROW',
  REMOVE_EMPTY_ROW: 'REMOVE_EMPTY_ROW',
  EDIT_START: 'SKILL_EDIT_START',
  EDIT_END: 'EDIT_END',
  EDIT_DATA: 'SKILL_EDIT_DATA',
  UPDATE: 'SKILL_UPDATE',
  REMOVE: 'SKILL_REMOVE',
};

export const MessageAction = {
  MESSAGE: 'INFO_MESSAGE',
};

export const HoverAction = {
  OVER: 'HOVER_OVER',
  OUT: 'HOVER_OUT',
};
